name: abc_project_2
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - simpleitk
  - pillow
  - scikit-learn
  - tqdm
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # for GPU support on compatible hardware
  - ome-zarr
  - zarr
  - dask
  - s3fs
  - monai
  - streamlit
  - pip
  - pip:
      - "abc_atlas_access[notebooks] @ git+https://github.com/alleninstitute/abc_atlas_access.git"

# conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
